language: python
env: TRAVIS_BUILD=1
python:
  - "3.6"
  - "nightly"
install: 
  - "pip3 install -r requirements.txt"
  - "pip3 install coverage"
  - "pip3 install codecov"
script:
  - "coverage run ./tests.py"
after_success: codecov